apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-storage
  namespace: vsphere-infra-helpers
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-csi